version: '3.8'
services:
  dotnet-app:
    image: your-registry/your-dotnet-app:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge