services:  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 3


# Data volumes
volumes:
  mongo-data: